server:
  port: 8081
  
spring:
  application:
    name: invoiceApp
    
  data:
    mongodb:
      authentication-database: admin
      auto-index-creation: true
      host: localhost
      port: 27017
      database: invoiceAP
      uri: mongodb://localhost:27017/invoiceAP
      
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s
